name: Node.js CI

on:
  push:
    branches: ["main"]
    paths:
      - "react-nuxt/**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        working-directory: react-vite # Adjust this path if necessary
        run: npm ci
      - name: Build and Test
        working-directory: react-vite # Adjust this path if necessary
        run: |
          npm run build --if-present
          npm test
